### PR TITLE
Unicode handling fixes

### LINKED ISSUE #2: Does not work when passed non-ascii via stdin
function `get_tokens_from_stdin` does not decode utf8 chars passed, so subsequent call in `process_start` using result of this fails

ref: https://github.com/amphp/parallel/issues/40

### PR DESCRIPTION
**Pull request by DaveRandom**
Fixes #2, closes #3.

[Version 2019.02.13.2](https://github.com/amphp/windows-process-wrapper/releases/tag/2019.02.13.2) has binaries attached. A quick test seems good - the amp/process test suite runs fine, and unicode paths appear to work correctly.

@trowski ping

### CODE REVIEW

**Comment by DaveRandom** [comment]
[Version 2019.02.13.3](https://github.com/amphp/windows-process-wrapper/releases/tag/2019.02.13.3) has builds of new commits.

**Comment by DaveRandom** [comment]
@ostrolucky do you have a decent real world test case for this? There isn't really a test suite for this utility, I have done a bit of contrived testing and I cannot find any issues, however my first language is English and as such I don't really deal with non-ASCII characters much. I haven't found any problems, but I'd really like some sort of 3rd party confirmation before I merge this and tag a stable release :-)

**Comment by ostrolucky** [comment]
Hey @DaveRandom, thanks for working on this. Decent reproducer is in https://github.com/amphp/parallel/issues/40 I will try this myself too

**Comment by ostrolucky** [comment]
It works on my side :)

**Comment by ostrolucky** [comment]
@DaveRandom will you merge this soon? Or who else do you need confirmation from?

**Comment by DaveRandom** [comment]
@ostrolucky https://github.com/amphp/process/pull/34 :slightly_smiling_face:

**Pull request merged**
